# Generated by Django 4.1.4 on 2022-12-25 17:42

import apps.cars.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=255)),
                ('year_release', models.IntegerField()),
                ('price', models.IntegerField()),
                ('seats_number', models.IntegerField()),
                ('body_type', models.CharField(max_length=255)),
                ('engine_volume', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_parks.autoparksmodel')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=apps.cars.services.upload_cars_photo)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carmodel')),
            ],
            options={
                'db_table': 'cars_photos',
            },
        ),
    ]
