# Generated by Django 4.1.4 on 2022-12-13 21:11

import django.db.models.deletion
from django.db import migrations, models

import backend.apps.cars.services


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=backend.apps.cars.services.upload_cars_photo)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_photos', to='cars.carmodel')),
            ],
            options={
                'db_table': 'cars_photos',
            },
        ),
    ]
