# Generated by Django 4.1.4 on 2022-12-14 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carphotomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphotomodel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carmodel'),
        ),
    ]
