# Generated by Django 4.1.4 on 2022-12-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carphotomodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
