# Generated by Django 4.1.4 on 2022-12-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'auto_parks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsersAutoParksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_parks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_parks.autoparksmodel')),
            ],
            options={
                'db_table': 'cars_auto_parks',
            },
        ),
    ]
