# Generated by Django 4.1.4 on 2022-12-25 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersautoparksmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoparksmodel',
            name='users',
            field=models.ManyToManyField(related_name='auto_parks', through='auto_parks.UsersAutoParksModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
