# Generated by Django 4.1.3 on 2022-12-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autoparksmodel',
            table='auto_parks',
        ),
    ]
