# Generated by Django 4.1.4 on 2022-12-23 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_parks', '0003_autoparksmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoparksmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='UsersAutoParksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_parks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_parks.autoparksmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cars_auto_parks',
            },
        ),
        migrations.AddField(
            model_name='autoparksmodel',
            name='users',
            field=models.ManyToManyField(related_name='auto_parks', through='auto_parks.UsersAutoParksModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
