# Generated by Django 4.1.3 on 2022-11-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=255)),
                ('year_release', models.IntegerField()),
                ('seats_number', models.IntegerField()),
                ('body_type', models.CharField(max_length=255)),
                ('engine_volume', models.FloatField()),
            ],
        ),
    ]
