# Generated by Django 4.1.3 on 2022-12-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_carmodel_auto_park'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='users',
        ),
    ]
